import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn } from 'typeorm';

export type KpiPeriodType = 'daily' | 'weekly' | 'monthly';

// A frozen KPI snapshot, one row per (project, assignee, period) -
// mirrors WeeklyReport's proven immutability pattern exactly: only ever
// inserted, never updated after the fact (see KpiService - there is no
// update/save-after-fetch method anywhere for this entity), so a later
// KpiConfig weight change has zero retroactive effect. weightsSnapshot
// embeds the exact weights used at generation time, so this row stays
// fully self-describing even if the config changes years later.
@Entity('kpi_period_score')
export class KpiPeriodScore {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  tenantId: number;

  @Column()
  projectId: number;

  @Column()
  projectName: string;

  @Column()
  assigneeUserId: number;

  @Column()
  assigneeEmail: string;

  @Column()
  periodType: KpiPeriodType;

  @Column({ type: 'date' })
  periodStart: string;

  @Column({ type: 'date' })
  periodEnd: string;

  @Column({ type: 'int' })
  ticketsDue: number;

  @Column({ type: 'int' })
  ticketsCompleted: number;

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  completionPercent: number;

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  hoursExceedPercent: number;

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  overduePercent: number;

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  targetMissPercent: number;

  @Column({ type: 'int' })
  qaRejectionCount: number;

  @Column({ default: false })
  excessiveRejectionFlag: boolean;

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  outboundDependencyOverduePercent: number;

  // Informational only, never penalized - never fed into compositeScore.
  @Column({ type: 'int' })
  inboundDependencyOverdueCount: number;

  @Column({ type: 'numeric', precision: 5, scale: 2 })
  compositeScore: number;

  // Monthly only: average of that month's already-frozen weekly rows'
  // compositeScore.
  @Column({ type: 'numeric', precision: 5, scale: 2, nullable: true })
  headlineScore: number;

  // Monthly only: recomputed directly from the month's raw counts, shown
  // alongside headlineScore so any drift between the two methods is
  // visible rather than hidden.
  @Column({ type: 'numeric', precision: 5, scale: 2, nullable: true })
  auditScore: number;

  // JSON-stringified snapshot of every weight/cap/threshold used to
  // compute this row - see the class comment above.
  @Column({ type: 'text' })
  weightsSnapshot: string;

  @CreateDateColumn()
  generatedAt: Date;

  // Null if generated by the scheduled cron job, set if triggered
  // manually - same convention as WeeklyReport.generatedByUserId.
  @Column({ nullable: true })
  generatedByUserId: number;
}
